site_name: Car Thing Hax
theme: 
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

copyright: Copyright &copy; 2024 Car Thing Hax, Maintained by the <a href="https://discord.gg/ZGURgxtaGM">Car Thing Hax Community</a>
